CREATE DATABASE IF NOT EXISTS internship_calendar;
USE internship_calendar;

DROP TABLE IF EXISTS calendar_events;
CREATE TABLE calendar_events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    week INT NOT NULL,
    day VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    success_criteria TEXT NOT NULL,
    traps TEXT DEFAULT NULL,
    event_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (1, 'Monday', 'Project kickoff and onboarding - Monday', 'Project kickoff and onboarding. Set up the workspace and learn the project goals. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Monday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-06-29');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (1, 'Tuesday', 'Project kickoff and onboarding - Tuesday', 'Project kickoff and onboarding. Map the requirements and prepare the workflow. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Tuesday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-06-30');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (1, 'Wednesday', 'Project kickoff and onboarding - Wednesday', 'Project kickoff and onboarding. Study the structure and plan the data model. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Wednesday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-01');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (1, 'Thursday', 'Project kickoff and onboarding - Thursday', 'Project kickoff and onboarding. Build the core pages and helper functions. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Thursday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-02');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (1, 'Friday', 'Project kickoff and onboarding - Friday', 'Project kickoff and onboarding. Review the work, close the loop, and document progress. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Friday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-03');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (2, 'Monday', 'UI planning and wireframes - Monday', 'UI planning and wireframes. Set up the workspace and learn the project goals. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Monday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-06');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (2, 'Tuesday', 'UI planning and wireframes - Tuesday', 'UI planning and wireframes. Map the requirements and prepare the workflow. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Tuesday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-07');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (2, 'Wednesday', 'UI planning and wireframes - Wednesday', 'UI planning and wireframes. Study the structure and plan the data model. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Wednesday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-08');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (2, 'Thursday', 'UI planning and wireframes - Thursday', 'UI planning and wireframes. Build the core pages and helper functions. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Thursday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-09');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (2, 'Friday', 'UI planning and wireframes - Friday', 'UI planning and wireframes. Review the work, close the loop, and document progress. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Friday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-10');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (3, 'Monday', 'Database design and modeling - Monday', 'Database design and modeling. Set up the workspace and learn the project goals. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Monday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-13');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (3, 'Tuesday', 'Database design and modeling - Tuesday', 'Database design and modeling. Map the requirements and prepare the workflow. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Tuesday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-14');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (3, 'Wednesday', 'Database design and modeling - Wednesday', 'Database design and modeling. Study the structure and plan the data model. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Wednesday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-15');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (3, 'Thursday', 'Database design and modeling - Thursday', 'Database design and modeling. Build the core pages and helper functions. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Thursday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-16');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (3, 'Friday', 'Database design and modeling - Friday', 'Database design and modeling. Review the work, close the loop, and document progress. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Friday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-17');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (4, 'Monday', 'PHP fundamentals and structure - Monday', 'PHP fundamentals and structure. Set up the workspace and learn the project goals. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Monday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-20');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (4, 'Tuesday', 'PHP fundamentals and structure - Tuesday', 'PHP fundamentals and structure. Map the requirements and prepare the workflow. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Tuesday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-21');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (4, 'Wednesday', 'PHP fundamentals and structure - Wednesday', 'PHP fundamentals and structure. Study the structure and plan the data model. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Wednesday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-22');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (4, 'Thursday', 'PHP fundamentals and structure - Thursday', 'PHP fundamentals and structure. Build the core pages and helper functions. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Thursday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-23');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (4, 'Friday', 'PHP fundamentals and structure - Friday', 'PHP fundamentals and structure. Review the work, close the loop, and document progress. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Friday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-24');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (5, 'Monday', 'CRUD implementation phase - Monday', 'CRUD implementation phase. Set up the workspace and learn the project goals. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Monday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-27');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (5, 'Tuesday', 'CRUD implementation phase - Tuesday', 'CRUD implementation phase. Map the requirements and prepare the workflow. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Tuesday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-28');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (5, 'Wednesday', 'CRUD implementation phase - Wednesday', 'CRUD implementation phase. Study the structure and plan the data model. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Wednesday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-29');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (5, 'Thursday', 'CRUD implementation phase - Thursday', 'CRUD implementation phase. Build the core pages and helper functions. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Thursday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-30');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (5, 'Friday', 'CRUD implementation phase - Friday', 'CRUD implementation phase. Review the work, close the loop, and document progress. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Friday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-07-31');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (6, 'Monday', 'Search, dashboard, and reporting - Monday', 'Search, dashboard, and reporting. Set up the workspace and learn the project goals. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Monday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-08-03');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (6, 'Tuesday', 'Search, dashboard, and reporting - Tuesday', 'Search, dashboard, and reporting. Map the requirements and prepare the workflow. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Tuesday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-08-04');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (6, 'Wednesday', 'Search, dashboard, and reporting - Wednesday', 'Search, dashboard, and reporting. Study the structure and plan the data model. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Wednesday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-08-05');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (6, 'Thursday', 'Search, dashboard, and reporting - Thursday', 'Search, dashboard, and reporting. Build the core pages and helper functions. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Thursday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-08-06');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (6, 'Friday', 'Search, dashboard, and reporting - Friday', 'Search, dashboard, and reporting. Review the work, close the loop, and document progress. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Friday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-08-07');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (7, 'Monday', 'Testing, polish, and refinement - Monday', 'Testing, polish, and refinement. Set up the workspace and learn the project goals. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Monday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-08-10');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (7, 'Tuesday', 'Testing, polish, and refinement - Tuesday', 'Testing, polish, and refinement. Map the requirements and prepare the workflow. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Tuesday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-08-11');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (7, 'Wednesday', 'Testing, polish, and refinement - Wednesday', 'Testing, polish, and refinement. Study the structure and plan the data model. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Wednesday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-08-12');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (7, 'Thursday', 'Testing, polish, and refinement - Thursday', 'Testing, polish, and refinement. Build the core pages and helper functions. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Thursday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-08-13');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (7, 'Friday', 'Testing, polish, and refinement - Friday', 'Testing, polish, and refinement. Review the work, close the loop, and document progress. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Friday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-08-14');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (8, 'Monday', 'Final review and presentation - Monday', 'Final review and presentation. Set up the workspace and learn the project goals. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Monday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-08-17');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (8, 'Tuesday', 'Final review and presentation - Tuesday', 'Final review and presentation. Map the requirements and prepare the workflow. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Tuesday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-08-18');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (8, 'Wednesday', 'Final review and presentation - Wednesday', 'Final review and presentation. Study the structure and plan the data model. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Wednesday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-08-19');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (8, 'Thursday', 'Final review and presentation - Thursday', 'Final review and presentation. Build the core pages and helper functions. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Thursday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-08-20');
INSERT INTO calendar_events (week, day, title, description, success_criteria, traps, event_date) VALUES (8, 'Friday', 'Final review and presentation - Friday', 'Final review and presentation. Review the work, close the loop, and document progress. Keep the notes updated and document progress inside the calendar system.', 'Complete the scheduled activity for Friday, capture the result, and prepare the next step for review.', 'Avoid skipping documentation, missing file names, or leaving the database plan inconsistent.', '2026-08-21');
